import { StyleSheet, TextStyle } from 'react-native';
import { colors, typography, spacing } from '../../theme';

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.background,
        justifyContent: 'space-between',
    },
    header: {
        width: '100%',
        backgroundColor: '#E5E5E5',
        alignItems: 'center',
        paddingVertical: spacing.xxl + spacing.xxl,
        paddingTop: spacing.xxl + spacing.xl,
    },
    logoText: {
        fontSize: 40,
        fontWeight: typography.weight.light as TextStyle['fontWeight'],
        marginBottom: spacing.l,
        fontFamily: typography.fonts.regular,
        color: colors.text.primary,
    },
    placeholderImage: {
        marginTop: spacing.m,
        justifyContent: 'center',
        alignItems: 'center',
    },
    form: {
        flex: 1,
        marginTop: spacing.xl,
        paddingHorizontal: spacing.l,
    },
    label: {
        fontSize: typography.size.caption,
        color: colors.text.secondary,
        marginBottom: spacing.xs,
        fontWeight: typography.weight.medium as TextStyle['fontWeight'],
    },
    input: {
        height: 50,
        backgroundColor: colors.background,
        borderRadius: spacing.s,
        paddingHorizontal: spacing.m,
        fontSize: typography.size.body,
        color: colors.text.primary,
        marginBottom: spacing.l,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    passwordContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        height: 50,
        backgroundColor: colors.background,
        borderRadius: spacing.s,
        paddingHorizontal: spacing.m,
        marginBottom: spacing.xs,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 3,
    },
    passwordInput: {
        flex: 1,
        height: 50,
        fontSize: typography.size.body,
        color: colors.text.primary,
    },
    eyeIcon: {
        fontSize: 18,
        color: colors.text.placeholder,
    },
    forgotPassword: {
        alignSelf: 'flex-end',
        color: colors.text.secondary,
        fontSize: typography.size.small,
        marginBottom: spacing.xl,
        marginTop: spacing.s,
    },
    signInButton: {
        backgroundColor: colors.primary,
        height: 44,
        width: 120,
        alignSelf: 'flex-end',
        borderRadius: spacing.s,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: spacing.l,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 5,
        elevation: 5,
    },
    signInButtonText: {
        color: colors.text.light,
        fontSize: typography.size.body,
        fontWeight: typography.weight.bold as TextStyle['fontWeight'],
    },
    signUpContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        marginBottom: spacing.xl,
    },
    signUpText: {
        color: colors.text.secondary,
        fontSize: typography.size.caption,
    },
    signUpLink: {
        color: colors.text.primary,
        textDecorationLine: 'underline',
        fontWeight: typography.weight.bold as TextStyle['fontWeight'],
        fontSize: typography.size.caption,
    },
    dividerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.l,
    },
    divider: {
        flex: 1,
        height: 1,
        backgroundColor: colors.border,
    },
    dividerText: {
        marginHorizontal: spacing.m,
        color: colors.text.secondary,
        fontSize: typography.size.small,
    },
    socialButtons: {
        flexDirection: 'row',
        justifyContent: 'center',
        gap: spacing.l,
    },
    socialButton: {
        width: 50,
        height: 50,
        backgroundColor: colors.background,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: spacing.s,
        borderWidth: 1,
        borderColor: colors.border,
    },
    guestButton: {
        alignSelf: 'flex-end',
        marginRight: spacing.l,
        marginBottom: spacing.l,
    },
    guestButtonText: {
        color: colors.text.secondary,
        fontSize: typography.size.caption,
    }
});
